name: CD - Deploy to VPS with PM2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy over SSH
        if: success()  # Աշխատի միայն եթե մինչև այս ամեն ինչ OK է
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd /home/${{ secrets.SSH_USERNAME }}/todo
            git reset --hard
            git pull origin main
            pm2 restart hsahakyanproject
          EOF
